### ISSUE TITLE
RuntimeError: Event loop is closed

### ISSUE THREAD

**Issue by hc0r3n00b** [DIGITALCRIMINALS/OnlyFans#232]
Getting the following error on fresh install of script & python. Updated script & installed requirements. 

`Traceback (most recent call last):
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 2207511814272

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 2207512219504

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 2207512219312

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 2207512219072

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\riley\Downloads\OnlyFans-master(3)\OnlyFans-master\start_ofd.py", line 77, in <module>
    asyncio.run(main())
  File "C:\Program Files\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\riley\Downloads\OnlyFans-master(3)\OnlyFans-master\start_ofd.py", line 62, in main
    api = await main_datascraper.start_datascraper(
  File "C:\Users\riley\Downloads\OnlyFans-master(3)\OnlyFans-master\datascraper\main_datascraper.py", line 69, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "C:\Users\riley\Downloads\OnlyFans-master(3)\OnlyFans-master\modules\onlyfans.py", line 110, in account_setup
    subscriptions += await manage_subscriptions(
  File "C:\Users\riley\Downloads\OnlyFans-master(3)\OnlyFans-master\modules\onlyfans.py", line 1264, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "C:\Users\riley\Downloads\OnlyFans-master(3)\OnlyFans-master\apis\onlyfans\classes\auth_model.py", line 279, in get_subscriptions
    json_authed = jsonpickle.encode(self, unpicklable=False)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 129, in encode
    context.flatten(value, reset=reset), indent=indent, separators=separators
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 255, in flatten
    return self._flatten(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 314, in _flatten_obj
    raise e
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 542, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.__dict__, data)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 584, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 658, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 314, in _flatten_obj
    raise e
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 542, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.__dict__, data)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 584, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 658, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 314, in _flatten_obj
    raise e
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 542, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.__dict__, data)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 584, in _flatten_dict_obj
    flatten(k, v, data)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 658, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 314, in _flatten_obj
    raise e
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "C:\Users\riley\AppData\Roaming\Python\Python310\site-packages\jsonpickle\pickler.py", line 507, in _flatten_obj_instance
    state = obj.__getstate__()
  File "C:\Program Files\Python310\lib\multiprocessing\queues.py", line 357, in __getstate__
    context.assert_spawning(self)
  File "C:\Program Files\Python310\lib\multiprocessing\context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance

Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000201F668A290>
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Program Files\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 745, in call_soon
    self._check_closed()
  File "C:\Program Files\Python310\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

**Comment by sintaxx** [comment]
i've been getting this as well today, worked fine last night.. i will try it with a different OF account and see if it still does it

**Comment by hc0r3n00b** [comment]
I have tried this in a new environment as well and still get the error

Hopefully @DIGITALCRIMINALS  can get this fixed soon, i have a subscription ending soon i need to download

**Comment by sintaxx** [comment]
I am also getting this after choosing my user profile

```
scraper@debian:~/OnlyFans$ python3.10 start_ofd.py
Choose Profile
Names: Username = username  | 0 = All | 1 = coro | 2 = OF666 | 3 = default
2
Auth (V1) Attempt 1/10
Welcome OFUser666 | OFUser666
Traceback (most recent call last):
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 139971325566336

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 139971325569216

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 139971325568496

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 262, in _flatten
    result = self._flattened[id(obj)]
KeyError: 139971325568208

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/scraper/OnlyFans/start_ofd.py", line 77, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/home/scraper/OnlyFans/start_ofd.py", line 62, in main
    api = await main_datascraper.start_datascraper(
  File "/home/scraper/OnlyFans/datascraper/main_datascraper.py", line 69, in start_datascraper
    setup, subscriptions = await module.account_setup(
  File "/home/scraper/OnlyFans/modules/onlyfans.py", line 110, in account_setup
    subscriptions += await manage_subscriptions(
  File "/home/scraper/OnlyFans/modules/onlyfans.py", line 1264, in manage_subscriptions
    results = await authed.get_subscriptions(identifiers=identifiers, refresh=refresh)
  File "/home/scraper/OnlyFans/apis/onlyfans/classes/auth_model.py", line 279, in get_subscriptions
    json_authed = jsonpickle.encode(self, unpicklable=False)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 129, in encode
    context.flatten(value, reset=reset), indent=indent, separators=separators
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 255, in flatten
    return self._flatten(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 314, in _flatten_obj
    raise e
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
 File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 542, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.__dict__, data)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 584, in _flatten_dict_obj
    flatten(k, v, data)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 658, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 314, in _flatten_obj
    raise e
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 542, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.__dict__, data)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 584, in _flatten_dict_obj
    flatten(k, v, data)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 658, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 314, in _flatten_obj
    raise e
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 542, in _flatten_obj_instance
    return self._flatten_dict_obj(obj.__dict__, data)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 584, in _flatten_dict_obj
    flatten(k, v, data)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 658, in _flatten_key_value_pair
    data[k] = self._flatten(v)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 264, in _flatten
    result = self._flattened[id(obj)] = self._flatten_impl(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 285, in _flatten_impl
    return self._pop(self._flatten_obj(obj))
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 314, in _flatten_obj
    raise e
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 308, in _flatten_obj
    return flatten_func(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 373, in _ref_obj_instance
    return self._flatten_obj_instance(obj)
  File "/home/scraper/.local/lib/python3.10/site-packages/jsonpickle/pickler.py", line 507, in _flatten_obj_instance
    state = obj.__getstate__()
  File "/usr/local/lib/python3.10/multiprocessing/queues.py", line 357, in __getstate__
    context.assert_spawning(self)
  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 359, in assert_spawning
    raise RuntimeError(
RuntimeError: SimpleQueue objects should only be shared between processes through inheritance```

**Comment by autisticvegan** [comment]
🛸same

**Comment by DIGITALCRIMINALS** [comment]
Use Python 3.10.1

**Comment by hc0r3n00b** [comment]
> Use Python 3.10.1

Still have this error.

**Comment by sintaxx** [comment]
Also still getting this error with 3.10.1

**Comment by sintaxx** [comment]
i'm out of ideas, i've even tried this with the docker container, same exact error. would this have anything to do with 2fa enabled on my account ?

**Comment by hc0r3n00b** [comment]
Me too, I’ve tried Debian, Ubuntu, arch & windows all with same error. I don’t have 2fa

**Comment by sintaxx** [comment]
> Use Python 3.10.1

anything else we can try ?

**Comment by DIGITALCRIMINALS** [comment]
Try latest commit

**Comment by DIGITALCRIMINALS** [comment]
Oh wait, you guys are using creator accounts, I'll check...

**Comment by DIGITALCRIMINALS** [comment]
Try latest commit

**Comment by sintaxx** [comment]
```Auth (V1) Attempt 1/10
Welcome User123 | User123Traceback (most recent call last):
  File "/mnt/truenas/porn/_SCRAPER/start_ofd.py", line 74, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/mnt/truenas/porn/_SCRAPER/start_ofd.py", line 61, in main
    api = await main_datascraper.start_datascraper(json_config, site_name_lower)
  File "/mnt/truenas/porn/_SCRAPER/datascraper/main_datascraper.py", line 110, in start_datascraper
    await default(datascraper)
  File "/mnt/truenas/porn/_SCRAPER/datascraper/main_datascraper.py", line 64, in default
    setup, subscriptions = await account_setup(
  File "/mnt/truenas/porn/_SCRAPER/helpers/main_helper.py", line 1023, in account_setup
    await datascraper.manage_subscriptions(
  File "/mnt/truenas/porn/_SCRAPER/modules/onlyfans.py", line 49, in manage_subscriptions
    site_settings = authed.api.get_site_settings()
AttributeError: 'create_auth' object has no attribute 'api'```

**Comment by DIGITALCRIMINALS** [comment]
It's fine, I know what's wrong with it since you're creators. I believe I fixed the problem in the latest commit.

**Comment by hc0r3n00b** [comment]
It works! Just in time before a subscription expires today!

**Comment by ProfessionalHorder** [comment]
This issue is back i'm afraid. On a regular account.

`Auth (V1) Attempt 1/10
Welcome 
Scraping Subscriptions
Scrape Processing
Name:  
Type: Stories
Traceback (most recent call last):
  File "D:\ofs\start_ofd.py", line 66, in <module>
    asyncio.run(main())
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "D:\ofs\start_ofd.py", line 52, in main
    api = await main_datascraper.start_datascraper(config, site_name)
  File "D:\ofs\datascraper\main_datascraper.py", line 131, in start_datascraper
    await default(datascraper)
  File "D:\ofs\datascraper\main_datascraper.py", line 101, in default
    await main_helper.process_jobs(datascraper, subscription_list, site_settings)
  File "D:\ofs\helpers\main_helper.py", line 1026, in process_jobs
    await datascraper.start_datascraper(authed, subscription.username)
  File "D:\ofs\modules\module_streamliner.py", line 84, in start_datascraper
    await self.prepare_scraper(subscription, content_type)
  File "D:\ofs\modules\module_streamliner.py", line 232, in prepare_scraper
    master_set.extend(await self.datascraper.get_all_stories(subscription))
  File "D:\ofs\modules\onlyfans.py", line 388, in get_all_stories
    highlights = await subscription.get_highlights()
  File "D:\ofs\apis\onlyfans\classes\user_model.py", line 283, in get_highlights
    results = [create_highlight(x) for x in results]
  File "D:\ofs\apis\onlyfans\classes\user_model.py", line 283, in <listcomp>
    results = [create_highlight(x) for x in results]
  File "D:\ofs\apis\onlyfans\classes\hightlight_model.py", line 3, in __init__
    self.id: int = option.get("id")
AttributeError: 'str' object has no attribute 'get'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000020C816F5A20>
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Users\\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`
