### ISSUE TITLE
All tge messages do not get scraped for avn

### ISSUE THREAD

**Issue by swagman382** [DIGITALCRIMINALS/OnlyFans#237]
Both paid and free messages are missing when scraping on avnstars

**Comment by DIGITALCRIMINALS** [comment]
Would you let me use your account to fix it?

**Comment by swagman382** [comment]
Yea sure, how can I send you the info?

**Comment by DIGITALCRIMINALS** [comment]
Have you tried the latest commit, maybe I've fixed it

**Comment by swagman382** [comment]
I went ahead and sent you an email as I am still getting an error

**Comment by DIGITALCRIMINALS** [comment]
@swagman382 emailed you back

**Comment by DIGITALCRIMINALS** [comment]
Thanks, I've fixed it in the latest commit

**Comment by swagman382** [comment]
Awesome, thanks!

**Comment by DIGITALCRIMINALS** [comment]
I also just added the ability to download items you bought

**Comment by swagman382** [comment]
Am I able to purchase messages using the scraper?
