### ISSUE TITLE
Issue downloading content onlyfans when auto_model_choice set to true

### ISSUE THREAD

**Issue by muggsyd** [DIGITALCRIMINALS/OnlyFans#27]
I am having an issue with scraping all models content when using "auto_model_choice": true from OnlyFans.

While the process does go through all the profiles I follow, it does not actually download any posts, videos or images, outside of their avatar or header.

However, when set to false, and manually typing in the number of the profile, it download all content as requested

**Comment by DIGITALCRIMINALS** [comment]
I can't do anything unless I have access to your account

**Comment by DIGITALCRIMINALS** [comment]
There's no logging option atm. I still can't recreate the issue.

What's your config settings?

**Comment by DIGITALCRIMINALS** [comment]
Sorry about this, it's fixed now - thanks.

**Comment by Servus7** [comment]
My master branch is up to date but the error still exists.
If auto_model_choice is set to true it doesn't download any post.

**Comment by Servus7** [comment]
Ok got it. It's scraping all models first and starts downloading afterwards. I was expecting it to scrape and download one model after another.
