### ISSUE TITLE
Not all content is being downloaded

### ISSUE THREAD

**Issue by offf1989** [DIGITALCRIMINALS/OnlyFans#316]
There are models where I can go and see messages on onlyfans and view videos and pictures, but they are not being downloaded when using this script.

It isn't consistent, for this particular model as an example, I have 3 new messages from her, there is one with a video and two pictures, and two with a video and a picture. The message with a video and two pictures is not being downloaded, but the other two with a video and a picture are being downloaded.

Not sure if this 2 pics and a video is a pattern or not, but that's the trend here.... Any suggestions?

**Comment by offf1989** [comment]
Stories from anyone aren't being downloaded either

**Comment by offf1989** [comment]
On another model, none of the content is downloading from messages. These messages are ones with two videos, and just one video. So it doesn't look like the packaging of it is a common thread...

**Comment by offf1989** [comment]
Well, if I do this as auto model choice, this actually starts to work, but selecting an individual model craps the bed for sure... Not sure why that is....

**Comment by DIGITALCRIMINALS** [comment]
Which site?

**Comment by evilwadewilson** [comment]
I'm having the not all content issue on Onlyfans.

**Comment by DIGITALCRIMINALS** [comment]
> I'm having the not all content issue on Onlyfans.

What's the models name and what is missing?

**Comment by evilwadewilson** [comment]
ciieraa is the model, and it's not downloading any videos. Her profile has 12, and I've paid for some as well.

**Comment by offf1989** [comment]
My problem is also with OnlyFans

**Comment by offf1989** [comment]
> Well, if I do this as auto model choice, this actually starts to work, but selecting an individual model craps the bed for sure... Not sure why that is....

Even with this option, today it doesn't seem to be consistently downloading everything from only fans again

**Comment by evilwadewilson** [comment]
Issue resolved here. For some reason, adding #ad to the ignore list ignores a lot of posts that don't have #ad in them. Removed it, and now all is downloading.

**Comment by offf1989** [comment]
Still having this issue, I've been keeping an eye for the last couple weeks and I've seen all posts just fine, but messages on OnlyFans are hit and miss.

Specifically videos from this model: https://onlyfans.com/chantel024 that were sent as freebies are not being downloaded.

**Comment by Kurosaki22** [comment]
I was able to resolve this issue for me by setting "auto_media_choice": true  instead of all or 0

**Comment by offf1989** [comment]
Even setting auto_media_choice to true, I'm still having problems with content in messages being downloaded

**Comment by offf1989** [comment]
> To fix content that is behind paid content or messages, I'd need access to the account via auth.json file since it's a personalised issue.

I've got a good example now, that isn't buried way back, how can I send you my auth.json and details of the specific issue?
