### ISSUE TITLE
Getting Auth 404 with Latest Pull/Python etc

### ISSUE THREAD

**Issue by PsychoSid** [DIGITALCRIMINALS/OnlyFans#34]
Hi,

Like https://github.com/DIGITALCRIMINALS/OnlyFans/issues/32

I am now getting 404's on Auth when moving to the latest commit/Python etc.
```
Auth (V1) Attempt 1/10
Auth 404'ed
```

I am running this on my seedbox where I don't have root but have compiled and run latest OpenSSL/Python reinstalled all the pip modules etc.

The above link references the certs but that seems to be OK.

```
$ python -m certifi
~/.local/lib/python3.10/site-packages/certifi/cacert.pem
$ ~/python/bin/pip install --upgrade --user certifi
Requirement already satisfied: certifi in ~/.local/lib/python3.10/site-packages (2021.10.8)
```

Anything else I can try here ?

Cheers

**Comment by PsychoSid** [comment]
Humm - thanks getting a "Try again in 15 seconds" message.

**Comment by d3ibis** [comment]
@PsychoSid , I'm facing this on mac ): everything is done as what is mentioned in tutorial, all latest versions and still 404'ed

**Comment by PsychoSid** [comment]
@d3ibis If you check the other issue on my original post that might solve it on OSX https://github.com/DIGITALCRIMINALS/OnlyFans/issues/32

**Comment by DIGITALCRIMINALS** [comment]
I assume this is resolved? I don't have Mac .-.

**Comment by PsychoSid** [comment]
It is for a Mac, this is still happening on my Debian seedbed (feral hosting). I suspect OF my have blocked their IP range.

**Comment by DIGITALCRIMINALS** [comment]
Ahh probably, they blocked VPS addresses before. You can buy a socks5 proxy and add it to the script config to bypass it
