### ISSUE TITLE
Sess login issue

### ISSUE THREAD

**Issue by Nido21100** [DIGITALCRIMINALS/OnlyFans#595]
Hey all, recently got an issues that whenever i update the sess id into the auth.json and run the script it immediately logs me out of the site, which inturn changes the sess and causes the script to fail. Been at this for about an hour now and its the same thing that happens.

Anyone able to help???

**Comment by rknightion** [comment]
I think OF have changed the login bit as I now get:
```Auth (V1) Attempt 1/10
Something went wrong. [29141B1D]
Auth (V1) Attempt 2/10
Something went wrong. [29141B1D]
Auth (V1) Attempt 3/10
Something went wrong. [29141B1D]```
Followed by being logged out.

I also noticed the cookie has changed slightly and now contains:
```csrf=random; auth_id=number; cookiesAccepted=true; __stripe_mid=random; sess=ed4nehcpmataup8a8s1jggcdj4; fp=random; ref_src=; st=random```

There's extra fields that weren't there before for me

**Comment by lEtranger1942** [comment]
Same here. Waiting for a fix or some ideas on how to tweak this

**Comment by RB1875** [comment]
> I think OF have changed the login bit as I now get: `Auth (V1) Attempt 1/10 Something went wrong. [29141B1D] Auth (V1) Attempt 2/10 Something went wrong. [29141B1D] Auth (V1) Attempt 3/10 Something went wrong. [29141B1D]`
> 
> Followed by being logged out of my session.
> 
> I also noticed the cookie has changed slightly and now contains:
> 
> `csrf=ra9DFw0Paaa62d038d158823998850a3; auth_id=1252411; cookiesAccepted=true; __stripe_mid=a360cccf-f89c-4233-9; sess=ed4nehcpmataup8a8s1jggcdj4; fp=28c65357aeb83124815658d0; ref_src=; st=0ba2f4498ddbbfb2a176cb350d1afa7651d5baa05e7e2441f9cd586` (values above indicative as anonymised) There's extra fields that weren't there before for me

very similar to you, but I don't have the __stripe_mid on any of my cookies, is this something that pops up if you use 2FA?

**Comment by rknightion** [comment]
> , is this something that pops up if you use 2FA?

I'm not using 2FA so don't think it's that. I'm assuming it's to do with their payment processor (which I think is still stripe) and the ability to quickly re-subscribe on the home page

**Comment by djmarioka** [comment]
Same issue here, since 2 or 3 days ago, maybe less:

![image](https://user-images.githubusercontent.com/81478245/185974767-54c3e04e-aa62-4585-a3ae-c5db7069058a.png)

**Comment by MacGargan** [comment]
I checked the scraper 2 days ago and it worked, so went ahead and bought a few bundles from favourite model, went to download today and it isn't working with this new error.

OF gods looking at me in shame for not subbing to anyone in months, so this is my punishment!

I know this was a very similar issue previously, hoping it's something similar again!

**Comment by icky7s** [comment]
The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine

**Comment by misterscraper** [comment]
> The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine

maybe give a more detailed approach to this fix, there isn't a "onlyfans.json"

**Comment by icky7s** [comment]
Sorry should've clarified the "onlyfans.json" is here https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json. The 'app_token' property is empty, but If you open your developer tools when logging into onlyfans you can see there's "app-token" header. If you add that header the requests complete with no issues. I added it to my own code to test and it works fine, to get everyone else's scrapers working it needs to be re-added to the "onlyfans.json" file.

**Comment by misterscraper** [comment]
> Sorry should've clarified the "onlyfans.json" is here https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json. The 'app_token' property is empty, but If you open your developer tools when logging into onlyfans you can see there's "app-token" header. If you add that header the requests complete with no issues. I added it to my own code to test and it works fine, to get everyone else's scrapers working it needs to be re-added to the "onlyfans.json" file.

Please give more details of the location, I cannot find this file anywhere in any directory when downloading the master .zip...

**Comment by Irock23** [comment]
> The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine

Hm, hardcoded the app-token value in api_helper.py, and now I'm getting "Please refresh the page".

**Comment by M-rcus** [comment]
In `.settings/config.json` find the line that looks like this:

```
"dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
```

Replace with:
```
"dynamic_rules_link": "https://i.marcus.pw/onlyfans.json",
```

I imagine that in the future you will have to revert that change, because I probably won't keep updating my copy, but that should be a temporary fix.

**Comment by Aer3x** [comment]
> > The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine
> 
> Hm, hardcoded the app-token value in api_helper.py, and now I'm getting "Please refresh the page".
Had the same issue, after adding
    "remove_headers": ["user-id"],
seen from @M-rcus his url, it did the job.

**Comment by misterscraper** [comment]
> In `.settings/config.json` find the line that looks like this:
> 
> ```
> "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> ```
> 
> Replace with:
> 
> ```
> "dynamic_rules_link": "https://i.marcus.pw/onlyfans.json",
> ```
> 
> I imagine that in the future you will have to revert that change, because I probably won't keep updating my copy, but that should be a temporary fix.

can confirm this works

**Comment by Egon099** [comment]
> 

How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever

**Comment by Egon099** [comment]
> > > The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine
> > 
> > 
> > Hm, hardcoded the app-token value in api_helper.py, and now I'm getting "Please refresh the page".
> 
> Had the same issue, after adding "remove_headers": ["user-id"], seen from @M-rcus his url, it did the job.

How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever

**Comment by marcintosch** [comment]
> How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever

Replace `global_settings: dict[str, Any] = {}
global_settings[
    "dynamic_rules_link"
] = "https://i.marcus.pw/onlyfans.json"`

with

global_settings: dict[str, Any] = {}
global_settings[
    "dynamic_rules_link"
] = "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"

until @DIGITALCRIMINALS provides the fix, then it works well again. Thanks to @M-rcus

**Comment by Irock23** [comment]
> > > The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine
> > 
> > 
> > Hm, hardcoded the app-token value in api_helper.py, and now I'm getting "Please refresh the page".
> 
> Had the same issue, after adding "remove_headers": ["user-id"], seen from @M-rcus his url, it did the job.

Removed user-id from create_headers, and that worked. Thanks!

> > > > The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine
> > > 
> > > 
> > > Hm, hardcoded the app-token value in api_helper.py, and now I'm getting "Please refresh the page".
> > 
> > 
> > Had the same issue, after adding "remove_headers": ["user-id"], seen from @M-rcus his url, it did the job.
> 
> How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever

At least assuming you're on the latest commit, you just replace this line:

> headers["app-token"] = dynamic_rules["app_token"]

with:

> headers["app-token"] = "33d57ade8c02dbc5a333db99ff9ae26a"

But the real long term fix is to fix the dynamic rules file.

**Comment by AlexDucks** [comment]
@Egon099 
> > > > The "app_token" header is missing in "onlyfans.json" and causing the errors, I manually pasted the header in my own code and it's working fine
> > > 
> > > 
> > > Hm, hardcoded the app-token value in api_helper.py, and now I'm getting "Please refresh the page".
> > 
> > 
> > Had the same issue, after adding "remove_headers": ["user-id"], seen from @M-rcus his url, it did the job.
> 
> How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever

Just to clarify here, I'll keep the link up, but since it's updated manually I can't guarantee that it'll work in the future. Simply because the normal "dynamic rules" link is auto-updated.

I'll have to go in and manually update it once they've fixed the values here: `https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json` (in which case, I'll simply add a "redirect" so that the data is the same as the file from "dynamic rules").

Anyways, I don't recommend modifying the code, but of course that's up to you.

@marcintosch 
> > How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever
> 
> Replace from line 43 on
> 
> `global_settings: dict[str, Any] = {} global_settings["dynamic_rules_link"] = "https://i.marcus.pw/onlyfans.json"`
> 
> with
> 
> `global_settings: dict[str, Any] = {} global_settings["dynamic_rules_link"] = "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"`
> 
> until @DIGITALCRIMINALS provides the fix, then it works well again. Thanks to @M-rcus

While this probably works, I don't know why you would do this over modifying the `.settings/config.json` file, which in my opinion is far easier.

**Comment by Irock23** [comment]
> > How do you code the token into api_helper.py to avoid using the link. Like they said they might not keep the link forever
> 
> Replace from line 43 on
> 
> `global_settings: dict[str, Any] = {} global_settings["dynamic_rules_link"] = "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json"`
> 
> with
> 
> `global_settings: dict[str, Any] = {} global_settings["dynamic_rules_link"] = "https://i.marcus.pw/onlyfans.json"`
> 
> until @DIGITALCRIMINALS provides the fix, then it works well again. Thanks to @M-rcus

This is not at all what I meant, and this makes no sense to do over changing config.json.

**Comment by M-rcus** [comment]
> EDIT: Just to clarify; I'll _probably_ keep updating my link with the correct values (I'll _redirect_ it to the original URL), but as I have to manually update it, it'll probably take a while after the dynamic-rules repository has been updated before I do so.

Added a small clarification at the end. TL;DR I'll update it, but it might not be "instant" like it would normally be.

**Comment by marcintosch** [comment]
> While this probably works, I don't know why you would do this over modifying the `.settings/config.json` file, which in my opinion is far easier.

Because on MacOS it doesn't work with changing '.settings/config.json' only, it seems like it will be read from DATAHOARDER as well. That's why I a clone of the api_helper.py and changed it to @M-rcus link, and then it works. Don't ask me why it doesn't work with editing the config.json alone on MacOS.

**Comment by M-rcus** [comment]
> > While this probably works, I don't know why you would do this over modifying the `.settings/config.json` file, which in my opinion is far easier.
> 
> Because on MacOS it doesn't work with changing '.settings/config.json' only, it seems like it will be read from DATAHOARDER nonetheless. That's why I made a clone of the api_helper.py and changed it to @M-rcus link, and then it works. Don't ask me why it doesn't work with editing the config.json alone on MacOS.

Did you make sure to _restart_ the script? As in, close it/cancel it with CMD+C(?) and then starting it up again?

It only loads the `dynamic_rules_link` on startup.

**Comment by Egon099** [comment]
I only asked because was curious

**Comment by marcintosch** [comment]
> Did you make sure to _restart_ the script? As in, close it/cancel it with CMD+C(?) and then starting it up again?
> 
> It only loads the `dynamic_rules_link` on startup.

Yes, I did, I tried several times on two Macs, even after a complete fresh restarts of the Mac Studio and the MacBook. It just started to work after the mentioned change in the api_helper as well. Makes no sense to me either btw.

**Comment by left1000** [comment]
> In `.settings/config.json` find the line that looks like this:
> 
> ```
> "dynamic_rules_link": "https://raw.githubusercontent.com/DATAHOARDERS/dynamic-rules/main/onlyfans.json",
> ```
> 
> Replace with:
> 
> ```
> "dynamic_rules_link": "https://i.marcus.pw/onlyfans.json",
> ```
> 
> I imagine that in the future you will have to revert that change, because I probably won't keep updating my copy, but that should be a temporary fix.
> 
> EDIT: Just to clarify; I'll _probably_ keep updating my link with the correct values (I'll _redirect_ it to the original URL), but as I have to manually update it, it'll probably take a while after the dynamic-rules repository has been updated before I do so.
> 
> EDIT 2: If your script is running, make sure to cancel/stop/shut down the script (CTRL+C) and then start it up again. It only loads dynamic rules on startup.

Not working for me, resulting in logging me out of the website, cookie has more values than it used to, wondering if the unneeded new cookie values need deleted? (although no one else indicated that step existed.)

Of course I tried so many times before reading this post that I am getting captcha on website login on my browser. So that could be the issue, I'll try again tomorrow and maybe on a first try it will work because I won't have failed 100 times in a row just before.

**Comment by silversurfer7702** [comment]
Made the change to the config.json as per mentioned above (replaced the url) and re-started.  Unfortunately still no dice, and I get this:

![image](https://user-images.githubusercontent.com/111753340/185994792-1a398a24-890b-4b78-9581-06b779c5bab9.png)

It also continually re-writes my OF auth.json file so I have to keep re-adding my username, etc.  Any ideas?  Thanks to everyone on here!

**Comment by fl4shbook** [comment]
Dynamic rules have been fixed !
https://github.com/DATAHOARDERS/dynamic-rules/commit/2a589ff2b4c379be917c273f4810610aa36ce3ff

Thanks @OFfriend

**Comment by nachoman91** [comment]
Sorry for being lost but how do we fix this? I dont even have a onlyfans.json file

**Comment by nachoman91** [comment]
> 

Same issue, no matter which dynamic rule im using. Am I missing something? SHould I replace a file or update something else?

**Comment by nachoman91** [comment]
> > Sorry for being lost but how do we fix this? I dont even have a onlyfans.json file
> 
> Simply restarting the script should solve the issue now.

Same issue, no matter which dynamic rule im using. Am I missing something? Should I replace a file or update something else?

**Comment by maxcom99** [comment]
Chiming in to say that I am also still having a login problem. I updated the cookie string to the latest from init, same error. Does anything else need to change?

**Comment by nachoman91** [comment]
> Chiming in to say that I am also still having a login problem. I updated the cookie string to the latest from init, same error. Does anything else need to change?

Dont know why but it works for me know.

**Comment by nachoman91** [comment]
> > > Sorry for being lost but how do we fix this? I dont even have a onlyfans.json file
> > 
> > 
> > Simply restarting the script should solve the issue now.
> 
> Same issue, no matter which dynamic rule im using. Am I missing something? Should I replace a file or update something else?

Dont know why but now its working for me

**Comment by fightcancer2** [comment]
> 

Editing the config.json worked for me.  Thanks!

**Comment by porncritic** [comment]
thanks for the temp fix M-rcus. back to orig. works great again. thank you all!!

**Comment by tythetiger0** [comment]
After the fix, I had to set up my `auth.json` again.

**Comment by OFfriend** [comment]
sorry! OF changed something. It's fixed now.

**Comment by JWeavis** [comment]
> sorry! OF changed something. It's fixed now.

Thanks!

**Comment by maxcom99** [comment]
> > sorry! OF changed something. It's fixed now.
> 
> Thanks!

Do we need to update the cookies? New params? Mine still not working.

**Comment by JWeavis** [comment]
> > > sorry! OF changed something. It's fixed now.
> > 
> > 
> > Thanks!
> 
> Do we need to update the cookies? New params? Mine still not working.

Close the script.  Login browser, update auth.json, run script.

**Comment by Bum211** [comment]
I was able to follow all the steps above and get the script to run but got a Keyerror: 'user_id"... any one got a clue on how to fix this, please? thanks!

**Comment by mbiasetti** [comment]
So what's the current fix folks? Sounds like we were replacing the URL in config.json for the dynamic rules, but now we shouldn't need to. Besides that, I saw someone hardcoded some of the auth values into the code itself. Is that still the current workaround? If not, what's actually working?

**Comment by mbiasetti** [comment]
So I actually just got it working. My problem was the x_bc header was not getting populated. I was stepping through the code and directly assigned it in the debugger, so I'm not sure how to properly add it. x_bc doesn't come through the cookie helper chrome plugin, I had to pull it from the developer tools.

I think you would want to add it to auth.json AFTER auth.json gets rewritten. Good luck.

**Comment by Bum211** [comment]
I have my x_bc in auth.json but when I tried to run the script, it just shut down completely now.. won't even show me what was the error. Did OF changed something? Does anyone have a working solution? please share

**Comment by mbiasetti** [comment]
Try adding the x_bc AFTER running the script because it rewrites the json
file during initialization. This version is currently working, you just got
to get your auth stuff worked out again, which is a pain.

**Comment by Bum211** [comment]
I tried that and i'm getting this now. 
![Screenshot 2022-08-24 110518](https://user-images.githubusercontent.com/96312987/186491103-d62d2925-9f3b-4811-9245-503c8969305b.jpg)

**Comment by Bum211** [comment]
> Thanks for the suggestion. I can log in now but I am still getting the 'user_ID' error. ;(

**Comment by M-rcus** [comment]
@Bum211 
> I have my x_bc in auth.json. When I run the script, this is the error I'm getting... anyone kind soul here know how to fix this, please? ![Screenshot 2022-08-24 100051](https://user-images.githubusercontent.com/96312987/186479070-fd33ac37-b98c-4e00-876e-b9fa516ae787.jpg)

I'm not 100% sure on this, but based on the error it seems to be related to the metadata. Try to rename (or delete) all your metadata folders to something else and re-run the script.

**Comment by Bum211** [comment]
> 

@M-rcus , thank you for your suggestion! The script finally works!!! Cheers!
